add giffgaff.init control file

diff --git a/giffgaff.init b/giffgaff.init
--- a/giffgaff.init
+++ b/giffgaff.init
@@ -1,11 +1,60 @@
 #!/bin/bash
 
+WORKER_NUM=2
+HOST="127.0.0.1"
+PORT="8000"
+PID_PATH="$PWD/pid"
+
 start() {
 	echo "Starting giffgaff.yongli1992.com"	
+	if [[ -f "$PID_PATH" ]]; then
+		pid=$(cat "$PID_PATH")
+		echo $"gunicorn is already running giffgaff with pid [$pid], please stop first."
+		exit 1
+	fi
+
+	echo "OK, no gunicorn giffgaff detected running."
+
+	# start the process
+	echo "Starting gunicorn giffgaff at $HOST:$PORT, pid path=$PID_PATH"
+	gunicorn --workers="$WORKER_NUM" -D index:app -b "$HOST":"$PORT" -p "$PID_PATH"
+
+	# check PID file created
+	sleep 0.5
+	if [[ -f "$PID_PATH" ]]; then
+		echo "Seen pid file created, started successfully."
+		exit 0
+	else
+		echo "Didn't see pid file created, failed to start."
+		exit 1
+	fi
 }
 
 stop() {
 	echo "Stopping giffgaff.yongli1992.com"
+	if [[ ! -f "$PID_PATH" ]]; then
+		echo "No pid file found, can't sotp"
+		exit 1
+	fi
+
+	pid=$(cat "$PID_PATH")
+	echo "Killing pid: $pid"
+	kill -9 "$pid"
+
+	echo "Removing pid file."
+	rm "$PID_PATH"
+
+	exit $?
+}
+
+status() {
+	if [[ -f "$PID_PATH" ]]; then
+		echo "Seen pid file, giffgaff is probably running at $HOST:$PORT."
+	else
+		echo "Didn't see pid file, giffgaff is probably not running."
+	fi
+
+	exit $?
 }
 
 case "$1" in
@@ -15,8 +64,11 @@ case "$1" in
 	stop)
 		stop
 	;;
+	status)
+		status
+	;;
 	*)
-		echo "Usage: {start|stop}"
+		echo "Usage: {start|stop|status}"
 		exit 1
 	;;
 esac
